### ISSUE TITLE
SAMD & STM32 packages need to be updated with appropriate driver installers

### ISSUE THREAD

**Issue by mukeshbharath** [mcci-catena/arduino-boards#19]
The Arduino SAMD & STM32 BSPs have to be updated with driver installers.

**Comment by terrillmoore** [comment]
Can you make pull requests with the appropriate additional comment, for each of the two packages (on the related repo)? Then we can merge, etc. Thanks!

**Comment by mukeshbharath** [comment]
Sure, I Just spoke to Sungjoon. I will update the driver installers on the resp. packages

**Comment by terrillmoore** [comment]
Closed by 9ec8d1e320c6575f52924d88595b36d358098fa0
