### ISSUE TITLE
V1.06 STM port Generic Serial doesn't work

### ISSUE THREAD

**Issue by terrillmoore** [mcci-catena/arduino-boards#3]
Somehow we regressed in V1.06.

Repro:
1. open examples>blinky
2. select Catena 4551
3. Tools>Serial interface: generic serial
4. Upload method: STLink
5. USB interface: none
6. Verify

You will get link errors (mentioning USB).

**Comment by chwon64** [comment]
This is expected result. USB serial will be enabled only if serial interface is disabled.

**Comment by terrillmoore** [comment]
Same thing works fine with V1.0.5. If I try to compile with V1.0.6, I cannot link. Something is broken in V1.0.5.

**Comment by terrillmoore** [comment]
I removed and reinstalled V1.0.6, and did a clean build, and the problem cleared up.
