### ISSUE TITLE
Catena 4551 Continuous reset while running via Battery power

### ISSUE THREAD

**Issue by svelmurugan92** [mcci-catena/arduino-boards#7]
During uploading firmware, If  USB interface -> "Enable USB device" option is selected. Then Catena 4551 radio resets continuously resetting while running in battery power. Same working fine with USB power. 

Recommendation, 
If want to run in battery power, During uploading firmware, In the tool setting select USB interface -> "None" and select serial interface -> "Generic serial"

**Comment by terrillmoore** [comment]
Replaced by https://github.com/mcci-catena/Arduino_Core_STM32/issues/9; now that we have the BSP posted, issues here should be only for the documentation in this package.
